name: checks-ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_call:

jobs:
  run-checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Run checks.sh
        run: ./scripts/checks.sh
