name: release-ci

env:
  TAG_PATTERN: 'rc-0.0.*'

on:
  push:
    tags:
      - rc-0.0.*
jobs:
  run-checks:
    uses: ./.github/workflows/checks-ci.yml

  build-release:
    name: release
    needs: [run-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Run release.sh
        run: ./scripts/release.sh
        env:
          ISSUE_ID: ${{ secrets.ISSUE_ID }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          ORG_ID: ${{ secrets.ORG_ID }}

      - name: Upload image as artifact
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ${{ env.DOCKER_IMAGE_NAME }}
