name: release-ci

env:
  TAG_PATTERN: 'rc-0.0.*'

on:
  push:
    tags:
      - rc-0.0.*
jobs:
  run-checks:
    uses: ./.github/workflows/checks-ci.yml

  build-release:
    name: release
    needs: [run-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Run release.sh
        run: ./scripts/release.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ${{ env.DOCKER_IMAGE_PATH }}
