name: release-ci

env:
  TAG_PATTERN: 'rc-0.0.*'

on:
  push:
    tags:
      - rc-0.0.*
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Run checks.sh
        run: ./scripts/checks.sh

      - name: Run release.sh
        run: ./scripts/release.sh
